version: 2
jobs:
  lint212_jdk8:
    docker:
      - image: hseeberger/scala-sbt:8u242_1.3.8_2.12.10
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.10! check
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  lint212_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.6_1.3.8_2.12.10
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.10! check
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  lint213_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.13.1! check
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test212_jdk8:
    docker:
      - image: hseeberger/scala-sbt:8u242_1.3.8_2.12.10
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.10! test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test212_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.6_1.3.8_2.12.10
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.10! test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  test213_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.6_1.3.8_2.13.1
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.13.1! test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

workflows:
  version: 2
  build:
    jobs:
      - lint212_jdk8
      - lint212_jdk11
      - lint213_jdk11
      - test212_jdk8:
          requires:
            - lint212_jdk8
      - test212_jdk11:
          requires:
            - lint212_jdk11
      - test213_jdk11:
          requires:
            - lint213_jdk11
      - release:
          context: Sonatype
          requires:
            - test212_jdk8
            - test212_jdk11
            - test213_jdk11